import type { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Romevic',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/colors-svgrepo-com.svg" type="image/svg+xml" />
      <body>{children}</body>
    </html>
  )
}
