import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import { Footer, Header } from "@/components/app";

export const metadata: Metadata = {
  title: "Romevic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/test-tube.svg" type="image/svg+xml" />
      <body>
        <div className="flex flex-col min-h-screen">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
